name: uoc20241pec1
channels:
  - defaults
dependencies:
  - imbalanced-learn=0.12.3
  - jupyter=1.1.1
  - matplotlib=3.9.1
  - numpy=2.1.1
  - pandas=2.2.3
  - python=3.12.6
  - scikit-learn=1.5.2
  - seaborn=0.13.2